### ISSUE TITLE
address not displayed in top 100 HAC addresses 

### ISSUE THREAD

**Issue by hacashaddcit** [hacash/service#6]
I have 2 addresses with enough coin to be in the top 100 list, however only 1 of the addresses is there. The other is not. I have not transacted for a very long time, so its not as if the blockchain just needs to catch up. Seems like a bug.

**Comment by hacashaddcit** [comment]
accidentally posted this under Service. I just posted to Explorer.

**Comment by jojoin** [comment]
There is indeed an issue with stats delay here, which will be redeveloped in the next release.
